name: Airflow DAG CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  airflow_dag_job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Adjust this to your Python version if necessary

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install apache-airflow
        pip install pandas numpy scikit-learn mlflow joblib

    - name: Initialize Airflow database
      run: |
        source venv/bin/activate
        airflow db init

    - name: Copy DAGs to Airflow DAGs folder
      run: |
        mkdir -p $AIRFLOW_HOME/dags
        cp dags/*.py $AIRFLOW_HOME/dags/

    - name: Copy dataset to the correct location
      run: |
        cp LoanApprovalPrediction.csv $AIRFLOW_HOME/LoanApprovalPrediction.csv

    - name: Run Airflow DAG
      run: |
        source venv/bin/activate
        airflow dags trigger loan_approval_prediction_new

    - name: Run Airflow scheduler
      run: |
        source venv/bin/activate
        airflow scheduler &
        sleep 10  # Give the scheduler time to start

    - name: Wait for DAG to complete
      run: |
        source venv/bin/activate
        airflow tasks state loan_approval_prediction_new load_data
        airflow tasks state loan_approval_prediction_new train_and_evaluate

    - name: Collect and store logs
      run: |
        mkdir -p logs
        cp $AIRFLOW_HOME/logs/* logs/
      if: failure()
      
    - name: Upload logs as artifact
      uses: actions/upload-artifact@v2
      with:
        name: airflow-logs
        path: logs/
