name: Airflow DAG Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'
    
    - name: Install dependencies
      run: |
        pip install apache-airflow pandas scikit-learn mlflow
    
    - name: Initialize Airflow DB
      run: |
        mkdir -p ~/.airflow
        export AIRFLOW_HOME=~/.airflow
        airflow db init
    
    - name: List DAGs
      run: |
        echo "Listing all DAGs..."
        airflow dags list --output json
    
    - name: Test DAG integrity
      run: |
        echo "Testing DAG integrity..."
        python -c "from airflow.models import DagBag; d = DagBag(); print('DAGs:', d.dags.keys())"
    
    - name: Run DAG tasks
      run: |
        mkdir -p ~/.airflow
        export AIRFLOW_HOME=~/.airflow
        airflow dags test loan_approval_prediction_new load_data 2024-08-18
        airflow dags test loan_approval_prediction_new train_and_evaluate 2024-08-18
